### PR TITLE
Updating branch guidance now that the shuffle is complete 

### PR DESCRIPTION
**Pull request by jasonmalinowski**

### CODE REVIEW

**Comment by jaredpar** [comment]
👍 

Can we just make this an MD in the repo so we don't have to do this?

**Comment by basoundr** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@jaredpar: the reason this is in the wiki is so there's a single statement of branch truth that's not in a branch. You can't have single truth if there's multiple copies.

**Comment by jaredpar** [comment]
> You can't have single truth if there's multiple copies.

There is a threading joke somewhere in here ...

**Pull request merged**
